### ISSUE TITLE
Minitest gets confused when db-query-matchers is required and thinks I have no tests to run

### ISSUE THREAD

**Issue by gkop** [brigade/db-query-matchers#12]
Awesome gem, folks! Thank you for sharing.

I have an app with both RSpec and Minitest test suites.

I installed db-query-matchers in my Gemfile in the usual way:

    group :test do
      ...
      gem 'db-query-matchers'
    end

When I run `rake test` (which belongs to Minitest) with db-query-matchers required, Minitest gets confused and thinks I don't have any tests to run.

My solution is very simple, I change my Gemfile to not require db-query-matchers:

    group :test do
      ...
      gem 'db-query-matchers', require: false
    end

And then I require db-query-matchers explicitly in spec/rails_helper.rb .

So no big deal, but thought it would nice to document so that other users running Minitest in addition to RSpec can make the easy fix.

**Comment by trotzig** [comment]
Thanks for sharing @gkop! I don't have much experience with Minitest so I don't know what could be going on here. Hopefully your workaround can be of help to others running into the same issue.
