### ISSUE TITLE
getting error (expected proc)

### ISSUE THREAD

**Issue by darena-mdsol** [brigade/db-query-matchers#23]
I'm trying to use your matcher in rspec to verify that a child model causes an update on the parent model - a `belongs_to` association. I'm getting error `wrong argument type ChildModel (expected Proc)`
```
subject { parent_model.child_models.create attribute1: value }
it { is_expected.to make_database_queries(matching: /UPDATE/, count: 1) }
```
produces:
```
TypeError:
       wrong argument type ChildModel (expected Proc)
     # .../.rvm/gems/ruby-2.3.3@.../gems/db-query-matchers-0.8.0/lib/db_query_matchers/make_database_queries.rb:59:in `block (2 levels) in <top (required)>'
     # ./spec/models/child_model_spec.rb:27:in `block (3 levels) in <top (required)>'
```
What am I doing wrong?

**Comment by trotzig** [comment]
I'm not 100% sure about this, but it looks like you have to make sure that the matcher is passed the subject block, not the result of executing it. Try something like 

```ruby
    it 'makes a query' do
      expect { subject }.to make_database_queries(matching: /UPDATE/, count: 1)
    end
```

**Comment by darena-mdsol** [comment]
@trotzig Thank you so much. It's work! 👍  I didn't realize the matcher expect a block. `is_expected` is just `expect(subject)` as a method arg.
